name: flutter_samples
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  fluttericon: ^2.0.0
  google_fonts: ^4.0.4
  ui_common:
    path: packages/ui_common/

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1


flutter:
  uses-material-design: true
